// 365 daily quotes aligned with Peter's vision
// Identity · Mindset · Execution · Sales · Leadership · Discipline

export const quotes: { text: string; author: string }[] = [
  { text: "Discipline equals freedom.", author: "Jocko Willink" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { text: "Do not pray for an easy life. Pray for the strength to endure a difficult one.", author: "Bruce Lee" },
  { text: "You are the average of the five people you spend the most time with.", author: "Jim Rohn" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "What you do speaks so loudly that I cannot hear what you say.", author: "Ralph Waldo Emerson" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Don't count the days. Make the days count.", author: "Muhammad Ali" },
  { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
  { text: "The best revenge is massive success.", author: "Frank Sinatra" },
  { text: "I attribute my success to this: I never gave or took any excuse.", author: "Florence Nightingale" },
  { text: "If you want to achieve greatness, stop asking for permission.", author: "Anonymous" },
  { text: "Things work out best for those who make the best of how things work out.", author: "John Wooden" },
  { text: "To live a creative life, we must lose our fear of being wrong.", author: "Anonymous" },
  { text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
  { text: "Trust because you are willing to accept the risk, not because it's safe or certain.", author: "Anonymous" },
  { text: "Take up one idea. Make that one idea your life.", author: "Swami Vivekananda" },
  { text: "All our dreams can come true, if we have the courage to pursue them.", author: "Walt Disney" },
  { text: "Good things come to people who wait, but better things come to those who go out and get them.", author: "Anonymous" },
  { text: "If you do what you always did, you will get what you always got.", author: "Anonymous" },
  { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { text: "When you stop chasing the wrong things, you give the right things a chance to catch you.", author: "Lolly Daskal" },
  { text: "We become what we think about most of the time, and that's the strangest secret.", author: "Earl Nightingale" },
  { text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
  { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
  { text: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
  { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
  { text: "The difference between who you are and who you want to be is what you do.", author: "Anonymous" },
  { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
  { text: "When I dare to be powerful, to use my strength in the service of my vision, it becomes less and less important whether I am afraid.", author: "Audre Lorde" },
  { text: "Whatever the mind of man can conceive and believe, it can achieve.", author: "Napoleon Hill" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.", author: "Jamie Paolinetti" },
  { text: "You take your life in your own hands, and what happens? A terrible thing: no one to blame.", author: "Erica Jong" },
  { text: "What's money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.", author: "Bob Dylan" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
  { text: "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.", author: "David Brinkley" },
  { text: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt" },
  { text: "The whole secret of a successful life is to find out what is one's destiny to do, and then do it.", author: "Henry Ford" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { text: "The ones who are crazy enough to think they can change the world, are the ones that do.", author: "Anonymous" },
  { text: "Don't raise your voice, improve your argument.", author: "Desmond Tutu" },
  { text: "Did I offer peace today? Did I bring a smile to someone's face?", author: "Henri Nouwen" },
  { text: "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.", author: "Henry Ford" },
  { text: "It's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln" },
  { text: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
  { text: "Either write something worth reading or do something worth writing.", author: "Benjamin Franklin" },
  { text: "Nothing is impossible, the word itself says 'I'm possible'.", author: "Audrey Hepburn" },
  { text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain" },
  { text: "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.", author: "Johann Wolfgang von Goethe" },
  { text: "The question isn't who is going to let me; it's who is going to stop me.", author: "Ayn Rand" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Build your own dreams, or someone else will hire you to build theirs.", author: "Farrah Gray" },
  { text: "Remember that not getting what you want is sometimes a wonderful stroke of luck.", author: "Dalai Lama" },
  { text: "You can't use up creativity. The more you use, the more you have.", author: "Maya Angelou" },
  { text: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { text: "You may be disappointed if you fail, but you are doomed if you don't try.", author: "Beverly Sills" },
  { text: "Life is not measured by the number of breaths we take, but by the moments that take our breath away.", author: "Maya Angelou" },
  { text: "Winning isn't everything, but wanting to win is.", author: "Vince Lombardi" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { text: "The mind is everything. What you think you become.", author: "Buddha" },
  { text: "The most common way people give up their power is by thinking they don't have any.", author: "Alice Walker" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { text: "An unexamined life is not worth living.", author: "Socrates" },
  { text: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", author: "Mother Teresa" },
  { text: "When you reach the end of your rope, tie a knot in it and hang on.", author: "Franklin D. Roosevelt" },
  { text: "Always remember that you are absolutely unique. Just like everyone else.", author: "Margaret Mead" },
  { text: "Don't go around saying the world owes you a living. The world owes you nothing.", author: "Mark Twain" },
  { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin" },
  { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche" },
  { text: "Anyone who stops learning is old, whether at twenty or eighty.", author: "Henry Ford" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { text: "Two roads diverged in a wood, and I took the one less traveled by.", author: "Robert Frost" },
  { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
  { text: "Every child is an artist. The problem is how to remain an artist once he grows up.", author: "Pablo Picasso" },
  { text: "You can never cross the ocean until you have the courage to lose sight of the shore.", author: "Christopher Columbus" },
  { text: "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", author: "Maya Angelou" },
  { text: "Either you run the day, or the day runs you.", author: "Jim Rohn" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain" },
  { text: "Too many of us are not living our dreams because we are living our fears.", author: "Les Brown" },
  { text: "I didn't fail the test. I just found 100 ways to do it wrong.", author: "Benjamin Franklin" },
  { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { text: "The person who says it cannot be done should not interrupt the person who is doing it.", author: "Chinese Proverb" },
  { text: "There are two types of people who will tell you that you cannot make a difference: those who are afraid to try and those who are afraid you will succeed.", author: "Ray Goforth" },
  { text: "Thinking should become your capital asset, no matter whatever ups and downs you come across in your life.", author: "A.P.J. Abdul Kalam" },
  { text: "I find that when you have a real interest in life and a curious life, that sleep is not the most important thing.", author: "Martha Stewart" },
  { text: "It is never too late to be what you might have been.", author: "George Eliot" },
  { text: "Life is what we make it, always has been, always will be.", author: "Grandma Moses" },
  { text: "The map is not the territory.", author: "Alfred Korzybski" },
  { text: "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", author: "Aristotle" },
  { text: "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.", author: "Jesus" },
  { text: "The secret of joy in work is contained in one word — excellence. To know how to do something well is to enjoy it.", author: "Pearl Buck" },
  { text: "We must balance conspicuous consumption with conscious capitalism.", author: "Kevin Kruse" },
  { text: "Life is not about finding yourself. Life is about creating yourself.", author: "Lolly Daskal" },
  { text: "Nothing in life is to be feared, it is only to be understood.", author: "Marie Curie" },
  { text: "If you look at what you have in life, you'll always have more.", author: "Oprah Winfrey" },
  { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { text: "I am not afraid of storms, for I am learning how to sail my ship.", author: "Louisa May Alcott" },
  { text: "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.", author: "Mark Twain" },
  { text: "Remember that not getting what you want is sometimes a wonderful stroke of luck.", author: "Dalai Lama" },
  { text: "You can't connect the dots looking forward; you can only connect them looking backward.", author: "Steve Jobs" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { text: "Believe and act as if it were impossible to fail.", author: "Charles Kettering" },
  { text: "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", author: "Jimmy Dean" },
  { text: "Ignorance is never out of style. It was in fashion yesterday, it is the rage today, and it will set the pace tomorrow.", author: "Frank Dane" },
  { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
  { text: "Learn from the mistakes of others. You can't live long enough to make them all yourself.", author: "Eleanor Roosevelt" },
  { text: "If opportunity doesn't knock, build a door.", author: "Milton Berle" },
  { text: "Eighty percent of success is showing up.", author: "Woody Allen" },
  { text: "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.", author: "Steve Jobs" },
  { text: "The whole secret of a successful life is to find out what is one's destiny to do, and then do it.", author: "Henry Ford" },
  { text: "You were born to win, but to be a winner, you must plan to win, prepare to win, and expect to win.", author: "Zig Ziglar" },
  { text: "If you don't design your own life plan, chances are you'll fall into someone else's plan.", author: "Jim Rohn" },
  { text: "If you genuinely want something, don't wait for it — teach yourself to be impatient.", author: "Gurbaksh Chahal" },
  { text: "Someone is sitting in the shade today because someone planted a tree a long time ago.", author: "Warren Buffett" },
  { text: "I would rather die of passion than of boredom.", author: "Vincent van Gogh" },
  { text: "A truly rich man is one whose children run into his arms when his hands are empty.", author: "Unknown" },
  { text: "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.", author: "Charles Darwin" },
  { text: "If you want to be happy, be.", author: "Leo Tolstoy" },
  { text: "What's done is done. What matters is what you do next.", author: "Anonymous" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { text: "We know what we are, but know not what we may be.", author: "William Shakespeare" },
  { text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
  { text: "Out of difficulties grow miracles.", author: "Jean de la Bruyere" },
  { text: "In order to succeed, we must first believe that we can.", author: "Nikos Kazantzakis" },
  { text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
  { text: "If you cannot do great things, do small things in a great way.", author: "Napoleon Hill" },
  { text: "Every strike brings me closer to the next home run.", author: "Babe Ruth" },
  { text: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
  { text: "I've missed more than 9000 shots in my career. I've lost almost 300 games. I've failed over and over again in my life. And that is why I succeed.", author: "Michael Jordan" },
  { text: "Don't wait. The time will never be just right.", author: "Napoleon Hill" },
  { text: "Keep your face always toward the sunshine — and shadows will fall behind you.", author: "Walt Whitman" },
  { text: "The most difficult thing is the decision to act, the rest is merely tenacity.", author: "Amelia Earhart" },
  { text: "How wonderful it is that nobody need wait a single moment before starting to improve the world.", author: "Anne Frank" },
  { text: "Make each day your masterpiece.", author: "John Wooden" },
  { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
  { text: "When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left.", author: "Erma Bombeck" },
  { text: "Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.", author: "Booker T. Washington" },
  { text: "Certain things catch your eye, but pursue only those that capture the heart.", author: "Ancient Indian Proverb" },
  { text: "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine.", author: "Roy T. Bennett" },
  { text: "Only put off until tomorrow what you are willing to die having left undone.", author: "Pablo Picasso" },
  { text: "You become what you believe.", author: "Oprah Winfrey" },
  { text: "The most common way people give up their power is by thinking they don't have any.", author: "Alice Walker" },
  { text: "You've got to get up every morning with determination if you're going to go to bed with satisfaction.", author: "George Lorimer" },
  { text: "Goals are not only absolutely necessary to motivate us. They are essential to really keep us alive.", author: "Robert Schuller" },
  { text: "We can't help everyone, but everyone can help someone.", author: "Ronald Reagan" },
  { text: "Where there is a will, there is a way. If there is a chance in a million that you can do something, anything, to keep what you want from ending, do it.", author: "Pauline Kael" },
  { text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
  { text: "Life is short, and it is here to be lived.", author: "Kate Winslet" },
  { text: "What seems to us as bitter trials are often blessings in disguise.", author: "Oscar Wilde" },
  { text: "You can't cross the sea merely by standing and staring at the water.", author: "Rabindranath Tagore" },
  { text: "Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver.", author: "Ayn Rand" },
  { text: "Always do your best. What you plant now, you will harvest later.", author: "Og Mandino" },
  { text: "Failure will never overtake me if my determination to succeed is strong enough.", author: "Og Mandino" },
  { text: "We aim above the mark to hit the mark.", author: "Ralph Waldo Emerson" },
  { text: "You were born to win. Start acting like it.", author: "Anonymous" },
  { text: "No one has ever become poor by giving.", author: "Anne Frank" },
  { text: "I am not a has-been. I am a will-be.", author: "Lauren Bacall" },
  { text: "The secret is to work less as individuals and more as a team.", author: "Alison Maxwell" },
  { text: "It's not about ideas. It's about making ideas happen.", author: "Scott Belsky" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "You build on failure. You use it as a stepping stone. Close the door on the past.", author: "Johnny Cash" },
  { text: "Perfection is not attainable, but if we chase perfection we can catch excellence.", author: "Vince Lombardi" },
  { text: "Try not to become a man of success. Rather become a man of value.", author: "Albert Einstein" },
  { text: "Nothing is less productive than to make more efficient what should not be done at all.", author: "Peter Drucker" },
  { text: "Give me six hours to chop down a tree and I will spend the first four sharpening the axe.", author: "Abraham Lincoln" },
  { text: "It's not whether you get knocked down, it's whether you get up.", author: "Vince Lombardi" },
  { text: "Earn your confidence. Build it brick by brick.", author: "Anonymous" },
  { text: "Sales is not about selling anymore, but about building trust and educating.", author: "Siva Devaki" },
  { text: "The best salespeople are the ones who listen the most.", author: "Anonymous" },
  { text: "Every sale has five basic obstacles: no need, no money, no hurry, no desire, no trust.", author: "Zig Ziglar" },
  { text: "People don't buy what you do; they buy why you do it.", author: "Simon Sinek" },
  { text: "You don't close a sale, you open a relationship.", author: "Patricia Fripp" },
  { text: "The secret to successful selling is making the customer feel understood.", author: "Anonymous" },
  { text: "Approach each customer with the idea of helping him solve a problem or achieve a goal.", author: "Brian Tracy" },
  { text: "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.", author: "Vince Lombardi" },
  { text: "The harder the battle, the sweeter the victory.", author: "Les Brown" },
  { text: "Hustle until you no longer need to introduce yourself.", author: "Anonymous" },
  { text: "Entrepreneurship is living a few years of your life like most people won't, so you can spend the rest of your life like most people can't.", author: "Anonymous" },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Anonymous" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "Anonymous" },
  { text: "Wake up with determination. Go to bed with satisfaction.", author: "Anonymous" },
  { text: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery" },
  { text: "Little things make big days.", author: "Anonymous" },
  { text: "It's going to be hard, but hard is not impossible.", author: "Anonymous" },
  { text: "Don't wait for opportunity. Create it.", author: "Anonymous" },
  { text: "First, solve the problem. Then, write the code.", author: "John Johnson" },
  { text: "Great things never come from comfort zones.", author: "Anonymous" },
  { text: "Dream it. Wish it. Do it.", author: "Anonymous" },
  { text: "Stay foolish to stay sane.", author: "Maxime Lagacé" },
  { text: "When nothing goes right, go left.", author: "Anonymous" },
  { text: "Try Again. Fail again. Fail better.", author: "Samuel Beckett" },
  { text: "I wake up every morning and think to myself: how far can I push this company in the next 24 hours.", author: "Leah Busque" },
  { text: "If people are doubting how far you can go, go so far that you can't hear them anymore.", author: "Michele Ruiz" },
  { text: "We need to accept that we won't always make the right decisions, that we'll screw up royally sometimes.", author: "Arianna Huffington" },
  { text: "Whenever you find yourself doubting how far you can go, just remember how far you have come.", author: "Anonymous" },
  { text: "We cannot solve problems with the kind of thinking we employed when we came up with them.", author: "Albert Einstein" },
  { text: "Learn as if you will live forever, live like you will die tomorrow.", author: "Mahatma Gandhi" },
  { text: "Stay away from those people who try to disparage your ambitions. Small minds will always do that, but great minds will give you a feeling that you can become great too.", author: "Mark Twain" },
  { text: "When you give joy to other people, you get more joy in return.", author: "Eleanor Roosevelt" },
  { text: "When you change your thoughts, remember to also change your world.", author: "Norman Vincent Peale" },
  { text: "It is only when we take chances, when our lives improve. The initial and the most difficult risk that we need to take is to become honest.", author: "Walter Anderson" },
  { text: "Nature has given us all the pieces required to achieve exceptional wellness and health, but has left it to us to put these pieces together.", author: "Diane McLaren" },
  { text: "If you want something you've never had, you must be willing to do something you've never done.", author: "Thomas Jefferson" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { text: "You get in life what you have the courage to ask for.", author: "Oprah Winfrey" },
  { text: "Always keep your eyes open. Keep watching. Because whatever you see can inspire you.", author: "Grace Coddington" },
  { text: "Every day may not be good but there is something good in every day.", author: "Alice Morse Earle" },
  { text: "With the right mindset, we can't lose — we either practice what we've learned or we learn what we need to practice.", author: "Noura" },
  { text: "Even if you're on the right track, you'll get run over if you just sit there.", author: "Will Rogers" },
  { text: "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears.", author: "Chantal Sutherland" },
  { text: "The real man smiles in trouble, gathers strength from distress, and grows brave by reflection.", author: "Thomas Paine" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "It is not the mountain we conquer but ourselves.", author: "Edmund Hillary" },
  { text: "If you want to fly, you have to give up what weighs you down.", author: "Roy T. Bennett" },
  { text: "Dedicate yourself to continuous personal improvement — you are your most precious resource.", author: "Brian Tracy" },
  { text: "Today is your opportunity to build the tomorrow you want.", author: "Ken Poirot" },
  { text: "I never dreamed about success, I worked for it.", author: "Estee Lauder" },
  { text: "The most valuable thing you can make is a mistake — you can't learn anything from being perfect.", author: "Adam Osborne" },
  { text: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
  { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { text: "An obstacle is often a stepping stone.", author: "Prescott Bush" },
  { text: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", author: "Thomas Edison" },
  { text: "All progress takes place outside the comfort zone.", author: "Michael John Bobak" },
  { text: "Work hard, be kind, and amazing things will happen.", author: "Conan O'Brien" },
  { text: "A goal is a dream with a deadline.", author: "Napoleon Hill" },
  { text: "You have to learn the rules of the game. And then you have to play better than anyone else.", author: "Albert Einstein" },
  { text: "Never let your memories be greater than your dreams.", author: "Doug Ivester" },
  { text: "If you genuinely want something, don't wait for it. Teach yourself to be impatient.", author: "Gurbaksh Chahal" },
  { text: "Never complain and never explain.", author: "Benjamin Disraeli" },
  { text: "Great acts are made up of small deeds.", author: "Lao Tzu" },
  { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { text: "The goal is not to be perfect by the end. The goal is to be better today.", author: "Simon Sinek" },
  { text: "Make mistakes, learn from them, and start over with greater intelligence.", author: "Henry Ford" },
  { text: "You can't build a reputation on what you are going to do.", author: "Henry Ford" },
  { text: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison" },
  { text: "Take responsibility for yourself. Your decisions determine who you are.", author: "Anonymous" },
  { text: "Nothing will work unless you do.", author: "Maya Angelou" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { text: "The measure of who we are is what we do with what we have.", author: "Vince Lombardi" },
  { text: "The authority you carry is built by what you do, not what you say.", author: "Anonymous" },
  { text: "Own your story. Own your decisions. Own your results.", author: "Anonymous" },
  { text: "Clarity leads to power. Know what you want and go get it.", author: "Anonymous" },
  { text: "Your reputation is built one call at a time.", author: "Anonymous" },
  { text: "Lead every room you walk into. That's who you are.", author: "Anonymous" },
  { text: "Take the call. Send the email. Make the move. Do it now.", author: "Anonymous" },
  { text: "The man who takes full responsibility has no one to blame — and no excuses to hide behind.", author: "Anonymous" },
  { text: "Your standard of living follows your standard of thinking.", author: "Anonymous" },
  { text: "Outwork everyone in the room. Then outwork them again.", author: "Anonymous" },
  { text: "Build an empire or work for someone building theirs. Choose.", author: "Anonymous" },
  { text: "Excuses are the nails used to build a house of failure.", author: "Don Wilder" },
  { text: "Stop overthinking. Start doing. Perfection is the enemy of done.", author: "Anonymous" },
  { text: "Every successful agency started with one client and a lot of belief.", author: "Anonymous" },
  { text: "The energy you bring to a call determines the outcome before you say a word.", author: "Anonymous" },
  { text: "You are the authority. Walk in like it.", author: "Anonymous" },
  { text: "Close the deal. Move to the next. Never stop.", author: "Anonymous" },
  { text: "Consistency beats talent when talent doesn't show up consistently.", author: "Anonymous" },
  { text: "Do it afraid. Do it tired. Just do it.", author: "Anonymous" },
  { text: "You are not your past results. You are your next decision.", author: "Anonymous" },
  { text: "The business grows when you do.", author: "Anonymous" },
  { text: "Every no is one step closer to a yes.", author: "Anonymous" },
  { text: "You can always make more money. You can't make more time. Use both wisely.", author: "Anonymous" },
  { text: "Speed is a superpower. Decide fast, act faster.", author: "Anonymous" },
  { text: "Revenue solves most problems. Go get the revenue.", author: "Anonymous" },
  { text: "Build systems, not just hustle.", author: "Anonymous" },
  { text: "The best investment you can make is in yourself.", author: "Warren Buffett" },
  { text: "Success is not built on success. It's built on failure, frustration, and sometimes catastrophe.", author: "Sumner Redstone" },
  { text: "Your clients are buying your confidence as much as your service.", author: "Anonymous" },
  { text: "You don't need to be the best. You need to be the most reliable.", author: "Anonymous" },
  { text: "Momentum is everything. Keep it moving.", author: "Anonymous" },
  { text: "The best version of you is built through daily decisions, not big moments.", author: "Anonymous" },
  { text: "Ship it. Learn. Improve. Repeat.", author: "Anonymous" },
  { text: "Make your work speak louder than your words.", author: "Anonymous" },
  { text: "Iron sharpens iron. Surround yourself with people who push you.", author: "Proverbs 27:17" },
  { text: "Show up fully. Every single day.", author: "Anonymous" },
  { text: "You can't put a limit on anything. The more you dream, the farther you get.", author: "Michael Phelps" },
  { text: "Take ownership of everything in your life. No exceptions.", author: "Jocko Willink" },
  { text: "Default: aggressive. Not passive. Never passive.", author: "Jocko Willink" },
  { text: "Relax. Look around. Make a call.", author: "Jocko Willink" },
  { text: "Get after it.", author: "Jocko Willink" },
  { text: "The goal is not comfort. The goal is growth.", author: "Anonymous" },
  { text: "Your future self is watching you right now through your memories.", author: "Aubrey de Grey" },
  { text: "The standard you walk past is the standard you accept.", author: "David Morrison" },
  { text: "It's supposed to be hard. If it were easy, everyone would do it.", author: "A League of Their Own" },
  { text: "Start before you're ready. Adjust on the fly.", author: "Anonymous" },
  { text: "Make the decision. Then make the decision right.", author: "Anonymous" },
  { text: "Your identity is your most powerful asset.", author: "Anonymous" },
  { text: "You are what you repeatedly do. Excellence is not an act but a habit.", author: "Aristotle" },
  { text: "The man who is prepared has his battle half fought.", author: "Miguel de Cervantes" },
  { text: "Act like the CEO you want to become.", author: "Anonymous" },
  { text: "The work you do while you procrastinate is probably the work you should be doing for the rest of your life.", author: "Jessica Hische" },
  { text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { text: "If you're not embarrassed by the first version of your product, you've launched too late.", author: "Reid Hoffman" },
  { text: "Ideas are easy. Execution is everything.", author: "John Doerr" },
  { text: "Train your mind to see the opportunity in every situation.", author: "Anonymous" },
  { text: "Persistence guarantees that results are inevitable.", author: "Paramahansa Yogananda" },
  { text: "You have to fight to reach your dream. You have to sacrifice and work hard for it.", author: "Lionel Messi" },
  { text: "There are no shortcuts to any place worth going.", author: "Beverly Sills" },
  { text: "You don't rise to the level of your goals. You fall to the level of your systems.", author: "James Clear" },
  { text: "Every action you take is a vote for the type of person you wish to become.", author: "James Clear" },
  { text: "Success is the product of daily habits — not once-in-a-lifetime transformations.", author: "James Clear" },
  { text: "You get what you work for, not what you wish for.", author: "Anonymous" },
  { text: "Move fast. Stay decisive. Never hesitate.", author: "Anonymous" },
  { text: "The right time is now. The right place is here. The right person is you.", author: "Anonymous" },
  { text: "Be so good they can't ignore you.", author: "Steve Martin" },
  { text: "Small daily improvements over time lead to stunning results.", author: "Robin Sharma" },
  { text: "Your biggest competitor is your past self.", author: "Anonymous" },
];

export function getDailyQuote(): { text: string; author: string } {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const oneDay = 1000 * 60 * 60 * 24;
  const dayOfYear = Math.floor(diff / oneDay);
  return quotes[dayOfYear % quotes.length];
}
